services:
  - type: web_service
    name: projets1l3-web
    env: docker
    branch: symfony
    repo: https://github.com/destrok03/projets1l3.git
    dockerfilePath: Dockerfile
    plan: starter
    region: oregon
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        value: "REPLACE_WITH_APP_SECRET"
      - key: DATABASE_URL
        value: "REPLACE_WITH_DATABASE_URL"
      - key: DEFAULT_URI
        value: "REPLACE_WITH_DEFAULT_URI"
      - key: APP_DEBUG
        value: "0"
      - key: VAR_DUMPER_SERVER
        value: ""
    healthCheckPath: /
    minInstances: 1
    maxInstances: 3
