# Configuration de la base de données PostgreSQL - NEON CLOUD (Production)
db.url=jdbc:postgresql://ep-wild-union-adt126ml-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
db.username=neondb_owner
db.password=npg_TjgUR0lyrMo9
db.driver=org.postgresql.Driver

# LOCAL PostgreSQL (Backup/Test)
# db.url=jdbc:postgresql://localhost:5432/brasil_burger
# db.username=postgres
# db.password=amina2003@

# Configuration des connexions
db.pool.minSize=5
db.pool.maxSize=20

# Configuration Cloudinary
cloudinary.cloud_name=dnbv97moc
cloudinary.api_key=436389169293518
cloudinary.api_secret=5_4uiT8oMojfcPkv3K7_b3OGRWE

# Configuration de l'application
app.name=Brasil Burger
app.version=1.0.0
app.environment=development
